const clientRoute = require("./routes/clients")
const medicamentRoute = require("./routes/medicament")
const oddonnaceRoute = require("./routes/ordonnance")
const errorRoute = require("./controler/errors")
const express = require("express")
const { urlencoded } = require('body-parser')
let app = express()
app.use(express.json())
app.use(express.urlencoded({ extended: false }))
app.listen(3000, () => console.log("server démmaré sur le port 3000"));
app.use("/client", clientRoute)
app.use("/medicament",medicamentRoute)
app.use("/ordonnance",oddonnaceRoute)
app.get("*", errorRoute.Error)
